# Generated by Django 4.1.5 on 2023-01-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_remove_donor_email_remove_donor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donated',
            field=models.DateField(null=True),
        ),
    ]
