# Generated by Django 4.1.5 on 2023-01-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_donor_last_donated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='lat',
        ),
    ]
