# Generated by Django 4.1.5 on 2023-01-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_remove_bloodrequest_lan_remove_bloodrequest_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
