# Generated by Django 4.1.5 on 2023-01-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
